### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by mahagadorn** [pearselab/r-world-mahagadorn#1]
Hi Will,

Can we set up office hours tomorrow to talk about issues I am having with my terrain.

Mal

**Comment by willpearse** [comment]
Sure. Can we go with 11am your time?

**Comment by willpearse** [comment]
...or you could just jump into https://appear.in/usubioprogramming right now if you prefer

**Comment by mahagadorn** [comment]
You had said not to work on the terrain part today, so I thought it was more appropriate to do it tomorrow.   But if you think we can have a quick conversation them maybe I will jump in??

**Comment by willpearse** [comment]
I've lost you (or you've lost me), sorry...

Try to focus on the function that takes as input a cell cell and returns what value that cell should have. You can then write the code to loop over all the cells later.

**Comment by willpearse** [comment]
I realise that this might be too early for you, but my last appointment finished much earlier than I expect. If you can come over to https://appear.in/usubioprogramming now, I can see you right away. More time for me means more time for you, so pop on over :D
